services:
  app:
    image: ghcr.io/cangerx/c-aihuabu:latest
    container_name: infinite-canvas
    ports:
      - "3000:3000"
    volumes:
      - ./data/uploads:/app/web/data/uploads
    restart: unless-stopped
